//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JundaOS_WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_info
    {
        public int site_id { get; set; }
        public string site_name { get; set; }
        public byte site_type { get; set; }
        public byte is_deleted { get; set; }
    }
}
