//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Junda_TruckArrangeEntities : DbContext
    {
        public Junda_TruckArrangeEntities()
            : base("name=Junda_TruckArrangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<permit_info> permit_info { get; set; }
        public virtual DbSet<site_info> site_info { get; set; }
        public virtual DbSet<truck_info> truck_info { get; set; }
        public virtual DbSet<truck_offline_record> truck_offline_record { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<user_record> user_record { get; set; }
        public virtual DbSet<truck_permit_relation> truck_permit_relation { get; set; }
        public virtual DbSet<pre_schedule> pre_schedule { get; set; }
        public virtual DbSet<truck_compensation> truck_compensation { get; set; }
        public virtual DbSet<task_record> task_record { get; set; }
        public virtual DbSet<truck_attend_record> truck_attend_record { get; set; }
    }
}
