//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_record
    {
        public short task_type { get; set; }
        public short day_ninght { get; set; }
        public int truck_count { get; set; }
        public int from_site_id { get; set; }
        public int to_site_id { get; set; }
        public int permit_id { get; set; }
        public System.DateTime send_time { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> operate_time { get; set; }
        public long task_id { get; set; }
    }
}
