//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class truck_info
    {
        public int truck_id { get; set; }
        public int truck_num { get; set; }
        public string driver_name { get; set; }
        public short truck_state { get; set; }
        public string truck_license { get; set; }
    }
}
